//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.25 at 07:24:36 PM AEDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mycorp.com/crm/schema/types", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mycorp.crm.schema.types;
