server:
  port: 9090
spring:
  application:
    name: crm-webservice
  datasource:
    url: jdbc:h2:mem:crmdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    schema: classpath:sql\schema.sql
    data: classpath:sql\data.sql    
  h2:
    console:
      enabled: true
      path: /h2console