
package com.mycorp.crm.schema.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://mycorp.com/crm/schema/types")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface CustomerPort {

	/**
	 * 
	 * @param getCustomerRequest
	 * @return returns com.mycorp.crm.schema.types.GetCustomerResponse
	 */
	@WebMethod
	@WebResult(name = "getCustomerResponse", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "getCustomerResponse")
	public GetCustomerResponse getCustomer(
			@WebParam(name = "getCustomerRequest", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "getCustomerRequest") GetCustomerRequest getCustomerRequest);

	/**
	 * 
	 * @param createCustomerRequest
	 * @return returns com.mycorp.crm.schema.types.CreateCustomerResponse
	 */
	@WebMethod
	@WebResult(name = "createCustomerResponse", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "createCustomerResponse")
	public CreateCustomerResponse createCustomer(
			@WebParam(name = "createCustomerRequest", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "createCustomerRequest") CreateCustomerRequest createCustomerRequest);

	/**
	 * 
	 * @param updateCustomerRequest
	 * @return returns com.mycorp.crm.schema.types.UpdateCustomerResponse
	 */
	@WebMethod
	@WebResult(name = "updateCustomerResponse", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "updateCustomerResponse")
	public UpdateCustomerResponse updateCustomer(
			@WebParam(name = "updateCustomerRequest", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "updateCustomerRequest") UpdateCustomerRequest updateCustomerRequest);

	/**
	 * 
	 * @param deleteCustomerRequest
	 * @return returns com.mycorp.crm.schema.types.DeleteCustomerResponse
	 */
	@WebMethod
	@WebResult(name = "deleteCustomerResponse", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "deleteCustomerResponse")
	public DeleteCustomerResponse deleteCustomer(
			@WebParam(name = "deleteCustomerRequest", targetNamespace = "http://mycorp.com/crm/schema/types", partName = "deleteCustomerRequest") DeleteCustomerRequest deleteCustomerRequest);

}
